## This file is a general .xdc for the Basys3 rev B board
## To use it in a project:
## - uncomment the lines corresponding to used pins
## - rename the used ports (in each line, after get_ports) according to the top level signal names in the project

# Clock signal
set_property PACKAGE_PIN W5 [get_ports a]							
	set_property IOSTANDARD LVCMOS33 [get_ports a]
	create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports a]
 
# Switches
set_property PACKAGE_PIN V17 [get_ports {challenge[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {challenge[0]}]
set_property PACKAGE_PIN V16 [get_ports {challenge[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {challenge[1]}]
set_property PACKAGE_PIN W16 [get_ports {challenge[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {challenge[2]}]
set_property PACKAGE_PIN W17 [get_ports {challenge[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {challenge[3]}]
set_property PACKAGE_PIN W15 [get_ports {challenge[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {challenge[4]}]
set_property PACKAGE_PIN V15 [get_ports {challenge[5]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {challenge[5]}]
set_property PACKAGE_PIN W14 [get_ports {challenge[6]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {challenge[6]}]
set_property PACKAGE_PIN W13 [get_ports {challenge[7]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {challenge[7]}]
set_property PACKAGE_PIN V2 [get_ports {challenge[8]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {challenge[8]}]
set_property PACKAGE_PIN T3 [get_ports {challenge[9]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {challenge[9]}]
set_property PACKAGE_PIN T2 [get_ports {challenge[10]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {challenge[10]}]
set_property PACKAGE_PIN R3 [get_ports {challenge[11]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {challenge[11]}]
set_property PACKAGE_PIN W2 [get_ports {challenge[12]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {challenge[12]}]
set_property PACKAGE_PIN U1 [get_ports {challenge[13]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {challenge[13]}]
set_property PACKAGE_PIN T1 [get_ports {challenge[14]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {challenge[14]}]
set_property PACKAGE_PIN R2 [get_ports {challenge[15]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {challenge[15]}]
 

# LEDs
set_property PACKAGE_PIN U16 [get_ports {response[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {response[0]}]
set_property PACKAGE_PIN E19 [get_ports {response[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {response[1]}]
set_property PACKAGE_PIN U19 [get_ports {response[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {response[2]}]
set_property PACKAGE_PIN V19 [get_ports {response[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {response[3]}]
set_property PACKAGE_PIN W18 [get_ports {response[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {response[4]}]
set_property PACKAGE_PIN U15 [get_ports {response[5]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {response[5]}]
set_property PACKAGE_PIN U14 [get_ports {response[6]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {response[6]}]
set_property PACKAGE_PIN V14 [get_ports {response[7]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {response[7]}]
set_property PACKAGE_PIN V13 [get_ports {response[8]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {response[8]}]
set_property PACKAGE_PIN V3 [get_ports {response[9]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {response[9]}]
set_property PACKAGE_PIN W3 [get_ports {response[10]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {response[10]}]
set_property PACKAGE_PIN U3 [get_ports {response[11]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {response[11]}]
set_property PACKAGE_PIN P3 [get_ports {response[12]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {response[12]}]
set_property PACKAGE_PIN N3 [get_ports {response[13]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {response[13]}]
set_property PACKAGE_PIN P1 [get_ports {response[14]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {response[14]}]
set_property PACKAGE_PIN L1 [get_ports {response[15]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {response[15]}]
	
	set_property CLOCK_DEDICATED_ROUTE VALUE[get_nets a]